export const animeMovies = [
	{
		animeId: "a-letter-to-momo-dub",
		animeTitle: "A Letter to Momo (Dub)",
		animeImg: "https://gogocdn.net/cover/a-letter-to-momo-dub.jpg",
		releasedDate: "2011",
		animeUrl: "https://gogoanime.film///category/a-letter-to-momo-dub",
	},
	{
		animeId: "a-starry-tale-dub",
		animeTitle: "A Starry Tale (Dub)",
		animeImg: "https://gogocdn.net/cover/a-starry-tale-dub.jpg",
		releasedDate: "2011",
		animeUrl: "https://gogoanime.film///category/a-starry-tale-dub",
	},
	{
		animeId: "a-tree-of-palme-dub",
		animeTitle: "A Tree of Palme (Dub)",
		animeImg: "https://gogocdn.net/cover/a-tree-of-palme-dub.jpg",
		releasedDate: "2003",
		animeUrl: "https://gogoanime.film///category/a-tree-of-palme-dub",
	},
	{
		animeId: "a-wind-named-amnesia",
		animeTitle: "A Wind Named Amnesia",
		animeImg: "https://gogocdn.net/images/anime/A/11114.jpg",
		releasedDate: "1990",
		animeUrl: "https://gogoanime.film///category/a-wind-named-amnesia",
	},
	{
		animeId: "a-wind-named-amnesia-dub",
		animeTitle: "A Wind Named Amnesia (Dub)",
		animeImg: "https://gogocdn.net/cover/a-wind-named-amnesia-dub.jpg",
		releasedDate: "1990",
		animeUrl: "https://gogoanime.film///category/a-wind-named-amnesia-dub",
	},
	{
		animeId: "a-li-ce",
		animeTitle: "A.LI.CE",
		animeImg: "https://gogocdn.net/cover/a-li-ce.png",
		releasedDate: "2000",
		animeUrl: "https://gogoanime.film///category/a-li-ce",
	},
	{
		animeId: "a-li-ce-dub",
		animeTitle: "A.LI.CE (Dub)",
		animeImg: "https://gogocdn.net/cover/a-li-ce-dub.png",
		releasedDate: "2000",
		animeUrl: "https://gogoanime.film///category/a-li-ce-dub",
	},
	{
		animeId: "aachi-and-ssipak",
		animeTitle: "Aachi and Ssipak",
		animeImg: "https://gogocdn.net/images/Aachi.jpg",
		releasedDate: "2006",
		animeUrl: "https://gogoanime.film///category/aachi-and-ssipak",
	},
	{
		animeId: "aachi-wa-ssipak-dub",
		animeTitle: "Aachi wa Ssipak (Dub)",
		animeImg: "https://gogocdn.net/cover/aachi-wa-ssipak-dub.jpg",
		releasedDate: "2006",
		animeUrl: "https://gogoanime.film///category/aachi-wa-ssipak-dub",
	},
	{
		animeId: "accel-world-infiniteburst",
		animeTitle: "Accel World: Infinite∞Burst",
		animeImg: "https://gogocdn.net/cover/accel-world-infiniteburst.png",
		releasedDate: "2016",
		animeUrl: "https://gogoanime.film///category/accel-world-infiniteburst",
	},
	{
		animeId: "accel-world-infiniteburst-dub",
		animeTitle: "Accel World: Infinite∞Burst (Dub)",
		animeImg: "https://gogocdn.net/cover/accel-world-infiniteburst-dub.png",
		releasedDate: "2016",
		animeUrl:
			"https://gogoanime.film///category/accel-world-infiniteburst-dub",
	},
	{
		animeId: "ace-wo-nerae-1979",
		animeTitle: "Ace wo Nerae! (1979)",
		animeImg: "https://gogocdn.net/cover/ace-wo-nerae-1979.png",
		releasedDate: "1979",
		animeUrl: "https://gogoanime.film///category/ace-wo-nerae-1979",
	},
	{
		animeId: "adieu-galaxy-express-999-dub",
		animeTitle: "Adieu Galaxy Express 999 (Dub)",
		animeImg: "https://gogocdn.net/cover/adieu-galaxy-express-999-dub.jpg",
		releasedDate: "1981",
		animeUrl:
			"https://gogoanime.film///category/adieu-galaxy-express-999-dub",
	},
	{
		animeId: "afro-samurai-dub",
		animeTitle: "Afro Samurai (Dub)",
		animeImg: "https://gogocdn.net/cover/afro-samurai-dub.jpg",
		releasedDate: "2007",
		animeUrl: "https://gogoanime.film///category/afro-samurai-dub",
	},
	{
		animeId: "afro-samurai-resurrection-dub",
		animeTitle: "Afro Samurai: Resurrection (Dub)",
		animeImg: "https://gogocdn.net/cover/afro-samurai-resurrection-dub.jpg",
		releasedDate: "2009",
		animeUrl:
			"https://gogoanime.film///category/afro-samurai-resurrection-dub",
	},
	{
		animeId: "ah-my-goddess-the-movie",
		animeTitle: "Ah! My Goddess The Movie",
		animeImg: "https://gogocdn.net/images/anime/A/73937.jpg",
		releasedDate: "2000",
		animeUrl: "https://gogoanime.film///category/ah-my-goddess-the-movie",
	},
	{
		animeId: "ah-my-goddess-the-movie-dub",
		animeTitle: "Ah! My Goddess: The Movie (Dub)",
		animeImg: "https://gogocdn.net/cover/ah-my-goddess-the-movie-dub.jpg",
		releasedDate: "2000",
		animeUrl:
			"https://gogoanime.film///category/ah-my-goddess-the-movie-dub",
	},
	{
		animeId: "ai-city",
		animeTitle: "Ai City",
		animeImg: "https://gogocdn.net/cover/ai-city.png",
		releasedDate: "1986",
		animeUrl: "https://gogoanime.film///category/ai-city",
	},
	{
		animeId: "ai-mai-moe-can-change",
		animeTitle: "Ai Mai! Moe Can Change!",
		animeImg: "https://gogocdn.net/images/Ai Mai Moe Can Change.jpg",
		releasedDate: "2012",
		animeUrl: "https://gogoanime.film///category/ai-mai-moe-can-change",
	},
	{
		animeId: "ai-no-utagoe-wo-kikasete",
		animeTitle: "Ai no Utagoe wo Kikasete",
		animeImg: "https://gogocdn.net/cover/ai-no-utagoe-wo-kikasete.png",
		releasedDate: "2021",
		animeUrl: "https://gogoanime.film///category/ai-no-utagoe-wo-kikasete",
	},
];
