// Generated by https://quicktype.io

export interface AnimeDetails {
	animeTitle: string;
	type: string;
	releasedDate: string;
	status: string;
	genres: string[];
	otherNames: string;
	synopsis: string;
	animeImg: string;
	totalEpisodes: string;
	episodesList: EpisodesList[];
}

export interface EpisodesList {
	episodeId: string;
	episodeNum: string;
	episodeUrl: string;
}
